# These are supported funding model platforms

ko_fi: https://ko-fi.com/chadlymasterson
custom: ['https://twitch.tv/chadlymasterson', 'https://youtube.com/@chadlymasterson', 'https://modrinth.com/user/chadlymasterson'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
